version: 2
updates:
  # Configuração para dependências PHP (Composer)
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "master"
    labels:
      - "dependencies"
      - "security"

  # Configuração para dependências JavaScript (npm)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "master"
    labels:
      - "dependencies"
      - "security" 